## Numpy Tutorials

It provides a high-performance multidimensional array object, and tools for working with these arrays. 

### What is an array

An array is a data structure that stores values of same data type. In Python, this is the main difference between arrays and lists. While python lists can contain values corresponding to different data types, arrays in python can only contain values corresponding to same data type

In [2]:
## initially Lets import numpy

import numpy as np

In [ ]:
# pip install numpy
#conda install numpy

In [3]:
my_lst=[1,2,3,4,5,6] 

In [4]:
type(my_lst)

list

In [6]:
my_lst=[1,2,3,4,5,6]   #one dimentional array

arr=np.array(my_lst)

In [7]:
print(arr)

[1 2 3 4 5 6]


In [8]:
type(arr)

numpy.ndarray

In [10]:
## check the shape of the array (number of rows and cols)

arr.shape

(6,)

In [14]:
# Convert it into two dimentional array
arr.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [19]:
## Multinested array
my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[9,7,6,8,12]

arr=np.array([my_lst1,my_lst2,my_lst3])

In [20]:
arr            

array([[ 1,  2,  3,  4,  5],
       [ 2,  3,  4,  5,  6],
       [ 9,  7,  6,  8, 12]])

In [17]:
type(arr)

numpy.ndarray

In [11]:
type(arr)

numpy.ndarray

In [12]:
arr.shape

(3, 5)

In [21]:
arr.reshape(3,5)

array([[ 1,  2,  3,  4,  5],
       [ 2,  3,  4,  5,  6],
       [ 9,  7,  6,  8, 12]])

In [22]:
## Get max number

print(arr.max())

12


In [23]:
mylist1 = [1,2,3,4,5,6,7,8]
mylist2 = [9,10,11,12,13]
mylist3 = [14,15,16,17,18,19]


In [24]:
arr=np.array([mylist1,mylist2,mylist3])

C:\Users\Shrikant Agrawal\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  """Entry point for launching an IPython kernel.


In [25]:
print(arr)

[list([1, 2, 3, 4, 5, 6, 7, 8]) list([9, 10, 11, 12, 13])
 list([14, 15, 16, 17, 18, 19])]


In [26]:
type(arr)

numpy.ndarray

In [27]:
arr.shape

(3,)

In [28]:
arr

array([list([1, 2, 3, 4, 5, 6, 7, 8]), list([9, 10, 11, 12, 13]),
       list([14, 15, 16, 17, 18, 19])], dtype=object)

In [29]:
## Create arrays and reshape

np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [30]:
arr2=np.arange(0,10).reshape(2,5)

In [31]:
arr2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [32]:
## random distribution
np.random.rand(3,4)

array([[0.95311968, 0.70992252, 0.8347892 , 0.7901103 ],
       [0.16217924, 0.50964722, 0.91188566, 0.17317566],
       [0.97495897, 0.85596914, 0.32868824, 0.80252642]])

In [33]:
arr_ex=np.random.randn(3,3)

In [34]:
arr_ex

array([[-0.90105144,  2.15427549, -0.1570914 ],
       [ 0.62037951, -0.60250368,  1.8838182 ],
       [ 0.39465686,  0.42521972, -0.33881575]])

In [36]:
np.random.randint(low=1, high=100, size=10)

array([56, 11, 82, 66, 30, 45, 93, 59, 67, 72])

In [38]:
np.random.randint(1,10,5)

array([5, 3, 4, 8, 2])

In [39]:
import random

In [40]:
random.sample(range(10, 100), 5)

[24, 91, 60, 49, 27]